version: '3.8'

services:
  frontend:
    build:
      context: ./BookManagementFrontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network

  backend:
    build:
      context: ./BookAPI
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - app-network

networks:
  app-network:
